package de.uni_potsdam.hpi.asg.delaymatch.measure;

/*
 * Copyright (C) 2016 - 2017 Norman Kluge
 * 
 * This file is part of ASGdelaymatch.
 * 
 * ASGdelaymatch is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ASGdelaymatch is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with ASGdelaymatch.  If not, see <http://www.gnu.org/licenses/>.
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import de.uni_potsdam.hpi.asg.common.iohelper.BasedirHelper;
import de.uni_potsdam.hpi.asg.common.iohelper.FileHelper;
import de.uni_potsdam.hpi.asg.common.iohelper.WorkingdirGenerator;
import de.uni_potsdam.hpi.asg.common.technology.Technology;
import de.uni_potsdam.hpi.asg.delaymatch.helper.AbstractScriptGenerator;
import de.uni_potsdam.hpi.asg.delaymatch.model.DelayMatchModule;
import de.uni_potsdam.hpi.asg.delaymatch.model.MeasureRecord;

public class MeasureScriptGenerator extends AbstractScriptGenerator {
    private static final Logger              logger              = LogManager.getLogger();

    private static final String              in_v_file           = "_measure_in.v";

    // generated by SimFlow
    private static final String              dc_sh_file          = "_measure.sh";
    private static final String              dc_tcl_file         = "_measure.tcl";

    // generated by scripts of SimFlow
    private static final String              dc_log_file         = "_measure.log";

    // template files
    private static final File                dc_sh_templatefile  = BasedirHelper.getFileInBasedir("templates/delay_measure.sh");
    private static final File                dc_tcl_templatefile = BasedirHelper.getFileInBasedir("templates/delay_measure.tcl");

    private static Map<String, List<String>> templates;

    private int                              turnid;
    private String                           name;
    private String                           localfolder;
    private Technology                       tech;

    private Map<String, DelayMatchModule>    modules;

    public static MeasureScriptGenerator create(int turnid, String name, File arg_origfile, Map<String, DelayMatchModule> modules, Technology tech) {
        if(templates == null) {
            //@formatter:off
            templates = readTemplateCodeSnippets(dc_tcl_templatefile, new String[]{
                "setup", "elab", "final",
                "measure_min_rise_rise", "measure_min_rise_fall", "measure_min_rise_both",
                "measure_min_fall_rise", "measure_min_fall_fall", "measure_min_fall_both",
                "measure_min_both_rise", "measure_min_both_fall", "measure_min_both_both",
                "measure_max_rise_rise", "measure_max_rise_fall", "measure_max_rise_both",
                "measure_max_fall_rise", "measure_max_fall_fall", "measure_max_fall_both",
                "measure_max_both_rise", "measure_max_both_fall", "measure_max_both_both",
            });
            //@formatter:on
            if(templates == null) {
                return null;
            }
        }

        if(!FileHelper.getInstance().copyfile(arg_origfile, turnid + "_" + name + in_v_file)) {
            return null;
        }

        return new MeasureScriptGenerator(turnid, name, modules, tech);
    }

    private MeasureScriptGenerator(int turnid, String name, Map<String, DelayMatchModule> modules, Technology tech) {
        this.turnid = turnid;
        this.modules = modules;
        this.tech = tech;
        this.name = name;
        localfolder = WorkingdirGenerator.getInstance().getWorkingdir();
    }

    public boolean generate() {
        String rmdcshfile = turnid + "_" + name + dc_sh_file;
        String dcshfile = localfolder + rmdcshfile;
        FileHelper.getInstance().copyfile(dc_sh_templatefile, new File(dcshfile));
        replaceInSh(localfolder + turnid + "_" + name + dc_sh_file);

        String dctclfile = localfolder + turnid + "_" + name + dc_tcl_file;
        List<String> tclfilecontent = new ArrayList<>();
        tclfilecontent.addAll(generateSetupTcl());

        for(DelayMatchModule mod : modules.values()) {
            if(!mod.getMeasureRecords().isEmpty()) {
                tclfilecontent.addAll(generateElabTcl(mod.getModuleName()));
                for(MeasureRecord rec : mod.getMeasureRecords().values()) {
                    tclfilecontent.addAll(generateMeasureTcl(rec, mod.getModuleName()));
                }
                mod.setMeasureOutputfile(turnid + "_" + name + "_" + mod.getModuleName() + dc_log_file);
            }
        }

        tclfilecontent.addAll(generateFinalTcl());
        if(!FileHelper.getInstance().writeFile(new File(dctclfile), tclfilecontent)) {
            return false;
        }

        return true;
    }

    private void replaceInSh(String filename) {
        try {
            File f = new File(filename);
            List<String> out = new ArrayList<String>();
            BufferedReader reader = new BufferedReader(new FileReader(f));
            String line = null;
            while((line = reader.readLine()) != null) {
                line = line.replace("#*dc_tcl*#", turnid + "_" + name + dc_tcl_file);
                out.add(line);
            }
            reader.close();
            FileHelper.getInstance().writeFile(new File(filename), out);
        } catch(IOException e) {
            e.printStackTrace();
        }
    }

    private List<String> generateSetupTcl() {
        if(!templates.containsKey("setup")) {
            logger.error("Setup template code not found");
            return null;
        }
        List<String> newlines = new ArrayList<>();
        for(String line : templates.get("setup")) {
            line = line.replace("#*orig*#", turnid + "_" + name + in_v_file);
            line = line.replace("#*dc_log*#", turnid + "_" + name + dc_log_file);
            line = line.replace("#*search_path*#", tech.getSynctool().getSearchPaths());
            line = line.replace("#*libraries*#", tech.getSynctool().getLibraries());
            newlines.add(line);
        }
        return newlines;
    }

    private List<String> generateElabTcl(String component) {
        if(!templates.containsKey("elab")) {
            logger.error("Elab template code not found");
            return null;
        }
        List<String> newlines = new ArrayList<>();
        for(String line : templates.get("elab")) {
            line = line.replace("#*dc_sub_log*#", turnid + "_" + name + "_" + component + dc_log_file);
            line = line.replace("#*root_sub*#", component);
            newlines.add(line);
        }
        return newlines;
    }

    private List<String> generateMeasureTcl(MeasureRecord rec, String component) {
        StringBuilder templateName = new StringBuilder();
        templateName.append("measure_");
        switch(rec.getType()) {
            case max:
                templateName.append("max_");
                break;
            case min:
                templateName.append("min_");
                break;
        }
        switch(rec.getFromEdge()) {
            case both:
                templateName.append("both_");
                break;
            case falling:
                templateName.append("fall_");
                break;
            case rising:
                templateName.append("rise_");
                break;
        }
        switch(rec.getToEdge()) {
            case both:
                templateName.append("both");
                break;
            case falling:
                templateName.append("fall");
                break;
            case rising:
                templateName.append("rise");
                break;
        }

        if(!templates.containsKey(templateName.toString())) {
            logger.error("Template code for " + templateName.toString() + " not found");
            return null;
        }

        String from = rec.getFromSignals();
        String to = rec.getToSignals();

        return generateMeasureCommonTcl(rec.getId(), component, from, to, templates.get(templateName.toString()));
    }

    private List<String> generateMeasureCommonTcl(String id, String component, String from, String to, List<String> lines) {
        List<String> newlines = new ArrayList<>();
        newlines.add("redirect -append " + turnid + "_" + name + "_" + component + dc_log_file + " {echo ASGdm\\;" + id + "\\;}");
        for(String line : lines) {
            line = line.replace("#*dc_sub_log*#", turnid + "_" + name + "_" + component + dc_log_file);
            line = line.replace("#*root_sub*#", component);
            line = line.replace("#*from_sub*#", from);
            line = line.replace("#*to_sub*#", to);
            newlines.add(line);
        }
        return newlines;
    }

    private List<String> generateFinalTcl() {
        if(!templates.containsKey("final")) {
            logger.error("Final template code not found");
            return null;
        }
        return templates.get("final");
    }

    public Set<String> getScriptFiles() {
        Set<String> retVal = new HashSet<>();
        retVal.add(localfolder + turnid + "_" + name + dc_sh_file);
        retVal.add(localfolder + turnid + "_" + name + dc_tcl_file);
        return retVal;
    }

    public String getExec() {
        return turnid + "_" + name + dc_sh_file;
    }

    public String getVInFile() {
        return localfolder + turnid + "_" + name + in_v_file;
    }
}
